# Generated by Django 5.0.6 on 2024-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="electronics",
            name="feature",
            field=models.CharField(default="Данные отсутсвуют", max_length=150),
        ),
    ]
